# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/Desktop/laser.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/Desktop/alwaysmiddle.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/alwaysinstr.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/splash.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_red.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_green.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_blue.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/pegasus_image.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_red_pegasus.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_green_pegasus.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_blue_pegasus.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/plane.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_red_plane.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_green_plane.coe
add_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/images/color_table_blue_plane.coe
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/divider_gen_synth_1/divider_gen.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/divider_gen_synth_1/divider_gen.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/laser_bram_synth_1/laser_bram.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/laser_bram_synth_1/laser_bram.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/always_bram_synth_1/always_bram.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/always_bram_synth_1/always_bram.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/video_bram2_synth_1/video_bram2.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/video_bram2_synth_1/video_bram2.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_bram_synth_1/splash_bram.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_bram_synth_1/splash_bram.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_red_table_synth_1/splash_red_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_red_table_synth_1/splash_red_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_green_table_synth_1/splash_green_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_green_table_synth_1/splash_green_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_blue_table_synth_1/splash_blue_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/splash_blue_table_synth_1/splash_blue_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_bram_synth_1/pegasus_bram.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_bram_synth_1/pegasus_bram.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_red_table_synth_1/pegasus_red_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_red_table_synth_1/pegasus_red_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_green_table_synth_1/pegasus_green_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_green_table_synth_1/pegasus_green_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_blue_table_synth_1/pegasus_blue_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/pegasus_blue_table_synth_1/pegasus_blue_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_bram_synth_1/plane_bram.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_bram_synth_1/plane_bram.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_red_table_synth_1/plane_red_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_red_table_synth_1/plane_red_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_green_table_synth_1/plane_green_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_green_table_synth_1/plane_green_table.dcp]
add_files -quiet /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_blue_table_synth_1/plane_blue_table.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.runs/plane_blue_table_synth_1/plane_blue_table.dcp]
read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/blobs.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/util.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/lfsr.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/SCCB_interface.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/OV7670_config_rom.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/OV7670_config.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/physics.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/pegasus.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/obstacles.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/ground.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/controller.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/sources/audio_PWM.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/rgb2hsv.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/motion_type.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/camera_read.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/camera_configure.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/sources/display_8hex.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/endscreen.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/new/attack.v
  /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/sources_1/imports/src/project_top.v
}
read_xdc /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master_lab4.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/t/a/taniayu/Desktop/6.111-final-project-master/project/project.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master_lab4.xdc]

catch { write_hwdef -file labkit.hwdef }
synth_design -top labkit -part xc7a100tcsg324-3
write_checkpoint -noxdef labkit.dcp
catch { report_utilization -file labkit_utilization_synth.rpt -pb labkit_utilization_synth.pb }
