# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram.xci
# IP: The module: 'video_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram.xci
# IP: The module: 'video_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
