# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram.xci
set_property is_locked true [get_files /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file video_bram.hwdef }
synth_design -top video_bram -part xc7a100tcsg324-3 -mode out_of_context
rename_ref -prefix_all video_bram_
write_checkpoint -noxdef video_bram.dcp
catch { report_utilization -file video_bram_utilization_synth.rpt -pb video_bram_utilization_synth.pb }
if { [catch {
  file copy -force /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.runs/video_bram_synth_1/video_bram.dcp /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.srcs/sources_1/ip/video_bram/video_bram_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
