webtalk_init -webtalk_dir /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 20 14:08:33 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2014.4.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1149489" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211027694_1777504441_210601152_408" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "32b14310-0268-42d8-97b3-ac414482c22d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "02f5260b-4b94-4c33-8fee-d31e63b2eee7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 12.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2826.214 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/Nexys4DDR/15000000:Xilinx/DLC9LP/6000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13631093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 3564028269 -regid "211027694_1777504441_210601152_408" -xml /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.hw/webtalk/usage_statistics_ext_labtool.xml -html /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.hw/webtalk/usage_statistics_ext_labtool.html -wdm /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/final_project/project_1.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
