# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table.xci
set_property used_in_implementation false [get_files -all /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table.dcp]
set_property is_locked true [get_files /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table.xci]

catch { write_hwdef -file red_table.hwdef }
synth_design -top red_table -part xc7a100tcsg324-3 -mode out_of_context
rename_ref -prefix_all red_table_
write_checkpoint -noxdef red_table.dcp
catch { report_utilization -file red_table_utilization_synth.rpt -pb red_table_utilization_synth.pb }
if { [catch {
  file copy -force /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.runs/red_table_synth_1/red_table.dcp /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /afs/athena.mit.edu/user/q/y/qyn/Desktop/6.111/images/project/project.srcs/sources_1/ip/red_table/red_table_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
